#!/usr/bin/python3
"""Factorize as many numbers as possible into
a product of two smaller numbers."""
from sys import argv


def factorize(value):
	""""Print an integer > 1 descomposition"""
	intgr = 2

	if value < 2:
		return
	print()
	print(value, "<- value-bef")
	while value % intgr:
		intgr += 1
	print("{:.0f}={:.0f}*{:.0f}".format(value, value / intgr, intgr))
	print(value, "<- value-aft")
	print()

if len(argv) != 2:
	exit()

try:
	with open(argv[1]) as file:
		line = file.readline()

		while line != "":
			value = int(line.split('\n')[0])
			factorize(value)
			line = file.readline()
except:
	pass
