#!/usr/bin/python3
"""Factorize as many numbers as possible into
a product of two smaller numbers."""
import sys


def factorize(number):
    """"Print an integer > 1 descomposition"""
    for i in range(2, number):
        if number % i == 0:
            return i, number // i
    return number, 1

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as file:
            numbers = file.readlines()
            for number in numbers:
                number = int(number.strip())
                factor1, factor2 = factorize(number)
                print(f"{number}={factor1}*{factor2}")
    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found.")
    except ValueError:
        print("Error: Invalid input in the file.")

if __name__ == "__main__":
    main()
